### ISSUE TITLE
copy method not working

### ISSUE THREAD

**Issue by naceee** [CMA-ES/moarchiving#12]
Hi, I'm Nace, a student of @ttusar and I'm working on extending this library to 3 and 4 dimensions. I tried using the `copy` method in the following way and it doesn't work:

```python
>>> from moarchiving2d import BiobjectiveNondominatedSortedList as moa2d
>>> m = moa2d([[1, 2], [2, 1]], [3, 3])
>>> m
[[1, 2], [2, 1]]
>>> m.copy()
E:\moarchiving\moarchiving\moarchiving2d.py:324: UserWarning: BiobjectiveNondominatedSortedList.copy has never been tested
  _warnings.warn('BiobjectiveNondominatedSortedList.copy has never been tested')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\moarchiving\moarchiving\moarchiving2d.py", line 327, in copy
    nda[d] = self[d]
TypeError: list indices must be integers or slices, not str
```

I tried fixing the issue by changing the line `nda[d] = self[d]` to `setattr(nda, d, getattr(self, d))` and now it doesn't throw the error anymore, but it doesn't create a deepcopy of the list either (and I'm not sure how to do it):

```python
>>> from moarchiving2d import BiobjectiveNondominatedSortedList as moa2d
>>> m = moa2d([[1, 2], [2, 1]], [3, 3])
>>> a = m.copy()
E:\moarchiving\moarchiving\moarchiving2d.py:324: UserWarning: BiobjectiveNondominatedSortedList.copy has never been tested
  _warnings.warn('BiobjectiveNondominatedSortedList.copy has never been tested')
>>> a
[[1, 2], [2, 1]]
>>> a[0][1] = 4 
>>> a
[[1, 4], [2, 1]]
>>> m
[[1, 4], [2, 1]]
```

**Comment by nikohansen** [comment]
I don't think it is expected to work. The obvious workaround is to create a deep `list` copy from the current `BiobjectiveNondominatedSortedList` (which is a `list`) and then create new `BiobjectiveNondominatedSortedList` instance from this `list` and the same reference point.

On the other hand, what is the use case for this? Something like `a[0][1] = 4` is not supposed to work properly anyway, because it may well put the class instance in an inconsistent state. AFAICS, from the users perspective, it should ideally throw an error. 

Generally, I am not sure I see why any element in the `BiobjectiveNondominatedSortedList` would ever need to be changed? I might be missing something, but I think the class also could (or should) be a list of (immutable) `tuple`s.

**Comment by nikohansen** [comment]
A simple fix to make the copy deep is probably to replace
```python
list.__init__(nda, self)
```
with
```python
list.__init__(self, (p[:] for p in self))
```

**Comment by naceee** [comment]
I agree that such use case is not likely, and probably shouldn't be allowed. I just wanted to point it out, as the function documentation says that it returns a "deep" copy (or maybe this is why deep is in the parenthesis?)

**Comment by naceee** [comment]
And to make it deep it should probably be like this right?
```python
list.__init__(nda, (p[:] for p in self))
```

**Comment by nikohansen** [comment]
> I agree that such use case is not likely, and probably shouldn't be allowed. I just wanted to point it out, as the function documentation says that it returns a "deep" copy (or maybe this is why deep is in the parenthesis?)

Yes, probably, I fixed the docstring.
